"""added votes table

Revision ID: 3ae139c63261
Revises: 96c056fc1375
Create Date: 2022-03-22 11:17:39.026046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae139c63261'
down_revision = '96c056fc1375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('upvoted', sa.Boolean(), nullable=False),
    sa.Column('downvoted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('answers', sa.Column('upvote_count', sa.Integer(), nullable=False))
    op.add_column('answers', sa.Column('downvote_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'downvote_count')
    op.drop_column('answers', 'upvote_count')
    op.drop_table('votes')
    # ### end Alembic commands ###
